Global:
  model_name: PP-OCRv5_kaggle_rec
  debug: false
  use_gpu: true
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: /kaggle/working/output/PP-OCRv5_kaggle_rec-ctc
  save_epoch_step: 1
  eval_batch_step: [0, 1000]
  cal_metric_during_train: true
  calc_epoch_interval: 1
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ./ppocr/utils/dict/amharic_dict.txt
  max_text_length: &max_text_length 150
  infer_mode: false
  use_space_char: true
  distributed: false
  save_res_path: /kaggle/working/output/rec/predicts_ppocrv5_kaggle.txt
  d2s_train_image_shape: [3, 48, 1280]

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 1
  regularizer:
    name: L2
    factor: 3.0e-05

Architecture:
  model_type: rec
  algorithm: SVTR_HGNet
  Transform:
  Backbone:
    name: PPHGNetV2_B4
    text_rec: True
  Head:
    name: CTCHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            kernel_size: [1, 3]
            use_guide: True
          Head:
            fc_decay: 0.00001
      #- NRTRHead:
     #     nrtr_dim: 384
      #    max_text_length: *max_text_length

Loss:
  name: CTCLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/input/datasets/kalafattezazu/cac-da-amh-ocr/CAC_DA_Amh_OCR/train
    ext_op_transform_idx: 1
    delimiter: "\t"
    label_file_list:
    - /kaggle/input/datasets/kalafattezazu/cac-da-amh-ocr/train_corrected - train_data.tsv
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug:
    -CTCLabelEncode:
    #- MultiLabelEncode:
    #    gtc_encode: NRTRLabelEncode
    - RecResizeImg:   # Crucial component added to guarantee uniform data mapping
        image_shape: [3, 48, 1280]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  sampler:
    name: MultiScaleSampler
    scales: [[1280, 32], [1280, 48], [1280, 64]]
    first_bs: &bs 8
    fix_bs: false
    divided_factor: [8, 16]
    is_training: True
  loader:
    shuffle: true
    batch_size_per_card: 32
    drop_last: true
    num_workers: 2

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/input/datasets/kalafattezazu/cac-da-amh-ocr/CAC_DA_Amh_OCR/test
    label_file_list:
    - /kaggle/input/datasets/kalafattezazu/cac-da-amh-ocr/test_corrected - test_data.tsv
    delimiter: "\t"
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
   # - MultiLabelEncode:
    #    gtc_encode: NRTRLabelEncode
    - CTCLabelEncode: # Changed from MultiLabelEncode
    - RecResizeImg:
        image_shape: [3, 48, 1280]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 32
    num_workers: 2
