Global:
  model_name: PP-OCRv5_server_rec_ctc_sentence_optimized
  debug: false
  use_gpu: true
  epoch_num: 150
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: /kaggle/working/output/PP-OCRv5_server_rec_ctc_sentence
  save_epoch_step: 1
  eval_batch_step: [0, 5000]
  cal_metric_during_train: true
  calc_epoch_interval: 1
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ./ppocr/utils/dict/amharic_dict.txt
  max_text_length: &max_text_length 150
  infer_mode: false
  use_space_char: true
  distributed: false
  save_res_path: /kaggle/working/output/rec/predicts_server_ctc_sentence.txt
  d2s_train_image_shape: [3, 64, 2048]


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0003
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 5.0e-05


Architecture:
  model_type: rec
  algorithm: SVTR_HGNet
  Transform:
  Backbone:
    name: PPHGNetV2_B4
    text_rec: True
  Neck:
    #name: SequenceEncoder
    #encoder_type: svtr  #reshape
    #dims: 160  # new
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 160
            depth: 4
            hidden_dims: 160
            kernel_size: [1, 3]
            use_guide: True
          Head:
            fc_decay: 0.0001
      - SARHead:
          enc_dim: 512
          max_text_length: *max_text_length # Ensure this matches your global max_text_length
Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - SARLoss:
    
PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: MultiScaleDataSet
    ds_width: false
    data_dir: /kaggle/input/datasets/teddylegessemunea/cac-da-amh-ocr/train
    ext_op_transform_idx: 1
    delimiter: "\t"
    label_file_list:
      - /kaggle/input/datasets/kalafattezazu/dataset/train.tsv
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.7
          ext_data_num: 3
          image_shape: [64, 2048, 3]
          max_text_length: *max_text_length
      - RecAug:
      - MultiLabelEncode: # Changed from CTCLabelEncode
          max_text_length: *max_text_length
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
            - label_sar
  sampler:
    name: MultiScaleSampler
    scales: [[2048, 48], [2048, 64], [2048, 80]]
    first_bs: &bs 16
    fix_bs: false
    divided_factor: [8, 16]
    is_training: True
  loader:
    shuffle: true
    batch_size_per_card: *bs
    drop_last: true
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/input/datasets/teddylegessemunea/cac-da-amh-ocr/val
    label_file_list:
      - /kaggle/input/datasets/kalafattezazu/dataset/val.tsv
    delimiter: "\t"
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - MultiLabelEncode: # Changed from CTCLabelEncode
          max_text_length: *max_text_length
      - RecResizeImg:
          eval_mode: True
          image_shape: [3, 64, 2048]
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
            - label_sar
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 4
